@echo on
SET PROJECTDIR=%1
SET SOLUTIONDIR=%2
SET CONFIGNAME=%3
SET TARGETDIR=%4

SET SFML_TARGET_DIR=%SOLUTIONDIR%..\extinclude\SFML\lib\%CONFIGNAME%\

xcopy %SFML_TARGET_DIR%*.dll %TARGETDIR% /Y /D